spring:
  ai:
    openai:
      api-key: sk-yawrwaegubvhovgtizsqgcsfynzanycuecjnsrpvscwmgtzc
      base-url: https://api.siliconflow.cn
      chat:
        options:
          model: deepseek-ai/DeepSeek-R1-0528-Qwen3-8B #模型名称
          temperature: 0.7  #模型温度，温度越高，结果越随机
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.ai.companion: debug
  charset:
    console: utf-8
    file: UTF-8